"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _react = require("react");

var _react2 = _interopRequireDefault(_react);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var BlueprintText = {
    title: "The Blueprint project Data Reuse statement",
    content: _react2.default.createElement(
        "div",
        null,
        _react2.default.createElement(
            "p",
            null,
            "This document refers to the reuse of data generated by the EC funded FP7 High Impact Project, Blueprint."
        ),
        _react2.default.createElement(
            "p",
            null,
            "Blueprint regularly released analysis results via its ftp site and makes the raw sequence data available through the sequence archives at the EMBL-EBI. Much Blueprint data is generated from samples whose data must be released through a managed access process. For these data sets external users must apply for permission to access the data from the European Genome-phenome Archive (EGA) through the Blueprint Data Access Committee."
        ),
        _react2.default.createElement(
            "p",
            null,
            "The Blueprint consortium expects this data to be valuable to other researchers and in keeping with Fort Lauderdale principles data users may use the data for many studies, but are expected to allow the data producers to make the first presentations and to publish the first paper with global analyses of the data."
        ),
        _react2.default.createElement(
            "h4",
            null,
            "Global analyses of Project data"
        ),
        _react2.default.createElement(
            "p",
            null,
            "Blueprint plans to publish global analyses of the sequencing data, epigenetic marks, expression levels and variation both in the context of normal hematopoietic cells and of those neoplastic and non-neoplastic diseases studied within the consortium. Talks, posters, and papers on all such analyses are to be published first by the Blueprint project, by approved presenters on behalf of the Project, with the Project as author. When the first major Project paper on these analyses is published, then researchers inside and outside the Project are free to present and publish using the Project data for these and other analyses."
        ),
        _react2.default.createElement(
            "h4",
            null,
            "Large-scale analyses of Project data"
        ),
        _react2.default.createElement(
            "p",
            null,
            "Groups within the Project may make presentations and publish papers on more extensive analyses of topics to be included in the main analysis presentations and papers, coincident with the main project analysis presentations and papers. The major points would be included in the main Project presentations and papers, but these additional presentations and papers allow more focused discussion of methods and results. The author list would include the Consortium."
        ),
        _react2.default.createElement(
            "h4",
            null,
            "Methods development using Project data"
        ),
        _react2.default.createElement(
            "p",
            null,
            "Researchers who have used small amounts of Project data (&lt= one chromosome) may present methods development posters, talks, and papers that include these data prior to the first major Project paper, without needing Project approval or authorship, although the Project should be acknowledged. Methods presentations or papers on global analyses or analyses using large amounts of Project data, on topics that the Consortium plans to examine, would be similar to large-scale analyses of Project data: researchers within the Project may make presentations or submit papers at the same time as the main Project presentations and papers, and others could do so after the Project publishes the first major analysis paper."
        ),
        _react2.default.createElement(
            "h4",
            null,
            "Disease studies using Project data"
        ),
        _react2.default.createElement(
            "p",
            null,
            "Researchers may present and publish on use of Project data in specific chromosome regions (that are not of general interest) or as summaries (such as number of differentially expressed genes in cell types assayed by Blueprint) for studies on diseases not studied by BLUEPRINT without Project approval, prior to the first major Project paper being published. The Project should not be listed as an author."
        ),
        _react2.default.createElement(
            "h4",
            null,
            "Authors who use data from the project must acknowledge Blueprint using the following wording"
        ),
        _react2.default.createElement(
            "p",
            null,
            "This study makes use of data generated by the Blueprint Consortium. A full list of the investigators who contributed to the generation of the data is available from",
            _react2.default.createElement(
                "a",
                { href: "http://www.blueprint-epigenome.eu" },
                "www.blueprint-epigenome.eu"
            ),
            ". Funding for the project was provided by the European Union's Seventh Framework Programme (FP7/2007-2013) under grant agreement no 282510 \u2013 BLUEPRINT."
        )
    )
};

var ZebrafishText = {
    title: "Data Reuse statement",
    content: _react2.default.createElement(
        "div",
        null,
        _react2.default.createElement(
            "p",
            null,
            "This is a pre-publication release in accordance with ",
            _react2.default.createElement(
                "a",
                { href: "http://www.sanger.ac.uk/datasharing/" },
                "the Fort Lauderdale Agreement "
            ),
            ". Feel free to search and download data on your genes of interest."
        ),
        _react2.default.createElement(
            "p",
            null,
            "Equally, you can use the dataset to show developmental expression profiles for specific genes in your publications."
        ),
        _react2.default.createElement(
            "p",
            null,
            "However, we ask that you refrain from publishing larger scale or genome-wide analyses of this dataset for 12 months from the time of deposition in Expression Atlas or until we have published our transcriptional time-course paper, whichever comes first."
        ),
        _react2.default.createElement(
            "p",
            null,
            "For citations in publications before the paper is out please use this link to the Expression Atlas site (",
            _react2.default.createElement(
                "a",
                { href: "https://www.ebi.ac.uk/gxa/experiments/E-ERAD-475" },
                "http://www.ebi.ac.uk/gxa/experiments/E-ERAD-475"
            ),
            ") and acknowledge us: \u201CWe would like to thank the Busch-Nentwich lab for providing RNA-seq data.\u201D"
        )
    )
};

var _default = { "fortLauderdale": BlueprintText, "zebrafish": ZebrafishText };
exports.default = _default;
;

var _temp = function () {
    if (typeof __REACT_HOT_LOADER__ === 'undefined') {
        return;
    }

    __REACT_HOT_LOADER__.register(BlueprintText, "BlueprintText", "src/manipulate/controls/download-button/Disclaimers.js");

    __REACT_HOT_LOADER__.register(ZebrafishText, "ZebrafishText", "src/manipulate/controls/download-button/Disclaimers.js");

    __REACT_HOT_LOADER__.register(_default, "default", "src/manipulate/controls/download-button/Disclaimers.js");
}();

;